kind: pipeline
type: docker
name: default

trigger:
  branch:
    - drone
    - standalone

publish: &publish
  image: buildpack-deps:22.04-scm
  commands:
    - ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
    - curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C /usr/local/bin
    - testspace config url $TESTSPACE_URL
    - testspace -v
    - printenv
    - |
      i=$CI_NODE_INDEX
      while [ "$i" -le 10 ]
      do
        export JOB=JOB-$i
        ./ts-time-push.sh
        i=$((i+$CI_NODE_TOTAL))
      done
  when:
    status: [ failure, success ]

steps:
- name: 'echo'
  image: buildpack-deps:22.04-scm
  commands:
    - echo step

- name: 'publish 1'
  <<: *publish
  environment:
    CI_NODE_INDEX: 1
    CI_NODE_TOTAL: 4
  depends_on:
    - echo

- name: 'publish 2'
  <<: *publish
  environment:
    CI_NODE_INDEX: 2
    CI_NODE_TOTAL: 4
  depends_on:
    - echo

- name: 'publish 3'
  <<: *publish
  environment:
    CI_NODE_INDEX: 3
    CI_NODE_TOTAL: 4
  depends_on:
    - echo

- name: 'publish 4'
  <<: *publish
  environment:
    CI_NODE_INDEX: 4
    CI_NODE_TOTAL: 4
  depends_on:
    - echo
