language: generic

branches:
  only:
    - standalone

before_install:
  - ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
  - mkdir -p $HOME/bin
  - curl -s https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | tar -zxvf- -C $HOME/bin
  - testspace config url "$TESTSPACE_URL/s2technologies:testspace.test.ci"
  - testspace -v

script:
  - printenv > printenv.txt
  - testspace config
  - cat $TRAVIS_BUILD_DIR/.testspace

after_script:
  - testspace results.xml printenv.txt "standalone#travis.$TRAVIS_BUILD_NUMBER" --repo=git --build-url=$TRAVIS_BUILD_WEB_URL
