version: 1.0.{build}

branches:
  only:
    - appveyor

shallow_clone: true
build: off

environment:
  matrix:
    - JOBS: 1 2 3 4 5
    - JOBS: 6 7 8 9 10

install:
  - call fix-hosts.bat && set /p TESTSPACE_URL=<testspace-url
  - appveyor DownloadFile https://testspace-client.s3.amazonaws.com/testspace-windows-dev.zip
  - 7z x -y testspace-windows-dev.zip
  - testspace config url %TESTSPACE_URL%
  - testspace -v

test_script:
  - ps: foreach ($n in $env:JOBS.Split(' ')) { $env:JOB = "JOB-$n"; cmd /c ts-time-push.bat }
