trigger:
  batch: true
  branches:
    include:
    - standalone
jobs:
- job: macOS

  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      ./fix-hosts.sh && TESTSPACE_URL=$(cat testspace-url)
      curl -s https://testspace-client.s3.amazonaws.com/testspace-darwin-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
      testspace config url "$TESTSPACE_URL/s2technologies:testspace.test.ci"
      testspace -v
    displayName: 'setup'
  - script: |
      printenv > printenv.txt
      testspace config
    displayName: 'echo'
  - script: |
      build_url="${SYSTEM_TEAMFOUNDATIONCOLLECTIONURI}${SYSTEM_TEAMPROJECTID}/_build/results?buildId=${BUILD_BUILDID}"
      echo $build_url
      testspace results.xml printenv.txt "standalone#azure.$BUILD_BUILDID" --repo=git --build-url=$build_url
    condition: always()
    displayName: 'publish'
