version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - run: echo "No CircleCI build on this branch"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circle
                - standalone
